---
- name: Install sudo permissions for main account
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: Add retackaberry to sudoers
      copy:
           dest: "/etc/sudoers.d/retackaberry"
           content: "retackaberry ALL=(ALL) NOPASSWD: ALL"