---

- hosts: servers
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"]  

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]  

