---

- name: master playbook
  hosts: all

- import_playbook: set_hostnames.yml
- import_playbook: upgrade_servers.yml
- import_playbook: install_packages.yml
- import_playbook: create_accounts.yml
- import_playbook: set_nameservers.yml
- import_playbook: set_static_address.yml
- import_playbook: reboot_system.yml
