---

- hosts: servers
  remote_user: retackaberry
  become: true
  vars:
    hostname: "{{ ansible_hostname}}"
    address: "{{ ansible_default_ipv4.address }}"
    macaddress: "{{ ansible_default_ipv4.macaddress|upper }}"
  
  tasks:
    - name: Remove old temporary j2 file
      ansible.builtin.file:
        path: macaddress_final.j2
        state: absent
      delegate_to: 127.0.0.1

    - name: Build j2 template
      template:
        src: macaddress_template.j2 
        dest: macaddress_final.j2
      delegate_to: 127.0.0.1
  
    - name: Wait for file to appear
      ansible.builtin.wait_for:
        path: macaddress_final.j2
        state: present
        msg: Timeout waiting for file to appear
      delegate_to: 127.0.0.1

- hosts: dhcp_servers
  remote_user: pi
  become: yes

  tasks:
    - name: Append the dhcp file on pihole  
      lineinfile:
        dest: /etc/dnsmasq.d/04-pihole-static-dhcp.conf
        line: "{{ lookup('file','macaddress_final.j2') }}"
        state: present

        
