---

- name: Update ubuntu servers
  hosts: ubuntu
  become: true
  tasks:
    - apt:
        update_cache: true
        upgrade: dist
        autoremove: true

- name: Update Raspbian servers
  hosts: raspbian
  tasks:
    - apt:
        update_cache: true 
        upgrade: dist
        autoremove: true

