---

- name: Setup Web Servers
  hosts: all
  become: true

  tasks:
  - name: install updates
    apt:
      upgrade: dist
      update_cache: true

- hosts: webservers
  become: true

  tasks: 
    - name: Install Apache2 and Apache2-bin on Ubuntu Servers
      apt:
        name: 
          - apache2
          - apache2-bin
          - apache2-utils
        state: latest
        update_cache: true

    - name: Enable Apache2 service
      systemd:
        name: "{{ web_service_name }}"

    - name: Deploy web content
      template:
        src: index.htm.j2
        dest: /var/www/html/index.htm
        owner: "{{ web_user_name }}"
        group: "{{ web_user_name }}"    

    - name: Move web content into the correct location
      copy:
        src: /var/www/html/index.htm
        remote_src: true
        dest: /var/www/html/index.html

    - name: Remove old htm file
      file:
        path: /var/www/html/index.htm
        state: absent  
        
- hosts: fileservers
  become: true
  
  tasks:
    - name: install samba package
      apt:
        name: samba
        state: latest
        update_cache: true
       
